version: '3.5'
services:
  database:
    build: ./mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: amazon
    ports:
      - 3306:3306
    volumes:
      - ./share/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    restart: always    
  backend:
    build: ./backend
    links:
      - database
    container_name: backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: amazon
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    depends_on:
      - always